server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/miyashop?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:miyashop}
    password: ${MYSQL_PASSWORD:miyashop2024}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

logging:
  level:
    com.miya: info
  file:
    name: /logs/miyashop/application.log